from qiime2.plugin import (
    SemanticType,
    Plugin,
    Int,
    Float,
    Range,
    Metadata,
    Str,
    Bool,
    Choices,
    MetadataColumn,
    Categorical,
    List,
    Citations,
    TypeMatch,
    Numeric,
)

glasso_parameters = {
    "n_samples": List[Int],
    "lambda1_min": List[Float],
    "lambda1_max": List[Float],
    "lambda2_min": List[Float],
    "lambda2_max": List[Float],
    "mu1_min": List[Float],
    "mu1_max": List[Float],
    "n_lambda1": Int,
    "n_lambda2": Int,
    "n_mu1": Int,
    "adapt_lambda1": List[Str],
    "latent": Bool,
    "non_conforming": Bool,
    "group_array": List[Int],
    "reg": Str,
    "gamma": Float
}